def COLOR_MAP = [
    'SUCCESS': 'good', 
    'FAILURE': 'danger',
]
pipeline {
    agent any
    
 environment {
        cluster = "saudevopsprojectprod"
        service = "saudevopsproject"
    }

    stages {
        

        stage('Deploy to ECS staging') {
            steps {
                withAWS(credentials: 'awscred', region: 'eu-north-1') {
                 sh 'aws ecs update-service --cluster ${cluster} --sevice ${service} --force-new-deployment'
                } 
            }
        }
    }
    post {
        always {
            echo 'Slack Notifications.'
            slackSend channel: '#bitirme-projesi',
                color: COLOR_MAP[currentBuild.currentResult],
                message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} \n More info at: ${env.BUILD_URL}"
        }
    }
}
